//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotPay.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotPay.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ABC {
            get {
                return ResourceManager.GetString("ABC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Alipay {
            get {
                return ResourceManager.GetString("Alipay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alipay TransferNo 的本地化字符串。
        /// </summary>
        internal static string alipay_transfer_no {
            get {
                return ResourceManager.GetString("alipay_transfer_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string BCM {
            get {
                return ResourceManager.GetString("BCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string BOC {
            get {
                return ResourceManager.GetString("BOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string CCB {
            get {
                return ResourceManager.GetString("CCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CNY 的本地化字符串。
        /// </summary>
        internal static string Chinese_Yuan {
            get {
                return ResourceManager.GetString("Chinese_Yuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string CIB {
            get {
                return ResourceManager.GetString("CIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string CMB {
            get {
                return ResourceManager.GetString("CMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string CMBC {
            get {
                return ResourceManager.GetString("CMBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Contact_us_via_QQ {
            get {
                return ResourceManager.GetString("Contact us via QQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copyright © 2014 Dotpay Technology co., LTD 的本地化字符串。
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Currently the Direct Transfer service charge 1‰, at least 2 CNY for fee, and for each transfer the amount is limited to 1-20000CNY. 的本地化字符串。
        /// </summary>
        internal static string Currently_the_Direct_Transfer_service_is_still_in_test_phase_it_s_free_and_for_each_transfer_the_amount_is_limited_to_1_1000CNY_ {
            get {
                return ResourceManager.GetString("Currently the Direct Transfer service is still in test phase,it\'s free and for ea" +
                        "ch transfer the amount is limited to 1-1000CNY.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Direct Transfer is a service provided by dotpay.co to enable &lt;a href=&quot;https://rippletrade.com/#/send&quot;  class=&quot;label label-info&quot;&gt;rippletrade client &lt;/a&gt;users to pay to Alipay account or bank account in China directly. 的本地化字符串。
        /// </summary>
        internal static string Direct_Transfer_is_a_service_provided_by_dotpay_co_to_enable_rippletrade_client_users_to_pay_to_Alipay_account_or_bank_account_in_China_directly_ {
            get {
                return ResourceManager.GetString("Direct Transfer is a service provided by dotpay.co to enable rippletrade client u" +
                        "sers to pay to Alipay account or bank account in China directly.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Direct_transfer_progress_query {
            get {
                return ResourceManager.GetString("Direct transfer progress query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Dotpay_your_fast_payment_expert {
            get {
                return ResourceManager.GetString("Dotpay,your fast payment expert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ECITIC {
            get {
                return ResourceManager.GetString("ECITIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Failed_Reason__0_ {
            get {
                return ResourceManager.GetString("Failed,Reason:{0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string GDB {
            get {
                return ResourceManager.GetString("GDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string HXB {
            get {
                return ResourceManager.GetString("HXB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ICBC {
            get {
                return ResourceManager.GetString("ICBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string If_you_just_created_the_transaction__please_you_5_minutes_before_query {
            get {
                return ResourceManager.GetString("If you just created the transaction, please you 5 minutes before query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string in_rippletrade_Recipient_blank_fill_in__0__for_paying_to_Alipay_account_or__1__for_bank_account__then_follow_the_emerging_instructions_to_fill_in_the_next_blanks_and_finally_confirm_the_payment_ {
            get {
                return ResourceManager.GetString("in rippletrade Recipient blank fill in {0} for paying to Alipay account or {1} fo" +
                        "r bank account, then follow the emerging instructions to fill in the next blanks" +
                        " and finally confirm the payment.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In working time (China working day 9:30-20:30, UTC+8:00 time zone), the transfer order will be processed in 2 hours, in non-working time it will be processed in 24 hours. 
        ///&lt;br&gt;
        ///To Alipay account, the payment will arrive real-time after being processed.&lt;br&gt;
        ///To bank account, it is estimated that the payment will arrive in 2 hours after the transfer order is processed, the actual time of arrival depends on the beneficiary bank. 的本地化字符串。
        /// </summary>
        internal static string In_work_time_the_transfer_will_be_done_in_no_greater_than_2_hours__if_there_is_no_delays_caused_by_force_majeures_such_as_ripple_system_issues__alipay_system_issues_or_bank_system_issues_ {
            get {
                return ResourceManager.GetString("In work time the transfer will be done in no greater than 2 hours, if there is no" +
                        " delays caused by force majeures such as ripple system issues, alipay system iss" +
                        "ues or bank system issues.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Instruction {
            get {
                return ResourceManager.GetString("Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click To Join Group 的本地化字符串。
        /// </summary>
        internal static string Join_QQ_group {
            get {
                return ResourceManager.GetString("Join QQ group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 For Support &amp; Info 的本地化字符串。
        /// </summary>
        internal static string Join_QQ_group_Title {
            get {
                return ResourceManager.GetString("Join QQ group Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Lastest_Transfer_Records {
            get {
                return ResourceManager.GetString("Lastest Transfer Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other Bank 的本地化字符串。
        /// </summary>
        internal static string OtherBank {
            get {
                return ResourceManager.GetString("OtherBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PAB {
            get {
                return ResourceManager.GetString("PAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Please_contact__0___for_next_step_processing {
            get {
                return ResourceManager.GetString("Please contact {0}  for next step processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Please_input__your_Ripple_TxId {
            get {
                return ResourceManager.GetString("Please input  your Ripple TxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PSBC {
            get {
                return ResourceManager.GetString("PSBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 not exist 的本地化字符串。
        /// </summary>
        internal static string ripple_query_not_exist {
            get {
                return ResourceManager.GetString("ripple_query_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done 的本地化字符串。
        /// </summary>
        internal static string ripple_query_status_Done {
            get {
                return ResourceManager.GetString("ripple_query_status_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        internal static string ripple_query_status_Failed {
            get {
                return ResourceManager.GetString("ripple_query_status_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pending 的本地化字符串。
        /// </summary>
        internal static string ripple_query_status_Processing {
            get {
                return ResourceManager.GetString("ripple_query_status_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amount 的本地化字符串。
        /// </summary>
        internal static string ripple_query_table_amount {
            get {
                return ResourceManager.GetString("ripple_query_table_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create At 的本地化字符串。
        /// </summary>
        internal static string ripple_query_table_create_at {
            get {
                return ResourceManager.GetString("ripple_query_table_create_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Done At 的本地化字符串。
        /// </summary>
        internal static string ripple_query_table_done_at {
            get {
                return ResourceManager.GetString("ripple_query_table_done_at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing Status 的本地化字符串。
        /// </summary>
        internal static string ripple_query_table_processing_status {
            get {
                return ResourceManager.GetString("ripple_query_table_processing_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receiver Account 的本地化字符串。
        /// </summary>
        internal static string ripple_query_table_receiver_account {
            get {
                return ResourceManager.GetString("ripple_query_table_receiver_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TransferNo 的本地化字符串。
        /// </summary>
        internal static string ripple_query_table_transferno {
            get {
                return ResourceManager.GetString("ripple_query_table_transferno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ripple TxId 的本地化字符串。
        /// </summary>
        internal static string ripple_query_table_txid {
            get {
                return ResourceManager.GetString("ripple_query_table_txid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        internal static string ripple_txid_query_btn_txt {
            get {
                return ResourceManager.GetString("ripple_txid_query_btn_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string SPDB {
            get {
                return ResourceManager.GetString("SPDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Support_Email {
            get {
                return ResourceManager.GetString("Support Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Tenpay {
            get {
                return ResourceManager.GetString("Tenpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer {0} CNY to {1} {2} 的本地化字符串。
        /// </summary>
        internal static string transfer__0__Yuan_to__1___2_ {
            get {
                return ResourceManager.GetString("transfer {0} Yuan to {1} {2}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Transfer_Information {
            get {
                return ResourceManager.GetString("Transfer Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Transfer_query {
            get {
                return ResourceManager.GetString("Transfer query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dotpay 的本地化字符串。
        /// </summary>
        internal static string website_Title {
            get {
                return ResourceManager.GetString("website_Title", resourceCulture);
            }
        }
    }
}
