//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dotpay.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dotpay.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Account_has_actived_ {
            get {
                return ResourceManager.GetString("Account has actived.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 click &lt;a href=&apos;/signin&apos; &gt;here &lt;/a&gt; to sign in . 的本地化字符串。
        /// </summary>
        internal static string activationDescription {
            get {
                return ResourceManager.GetString("activationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Almost_free {
            get {
                return ResourceManager.GetString("Almost free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Alread_have_an_account_ {
            get {
                return ResourceManager.GetString("Alread have an account?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string As_fast_as_send_a_email {
            get {
                return ResourceManager.GetString("As fast as send a email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ABC 的本地化字符串。
        /// </summary>
        internal static string BankABC {
            get {
                return ResourceManager.GetString("BankABC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BCM 的本地化字符串。
        /// </summary>
        internal static string BankBCM {
            get {
                return ResourceManager.GetString("BankBCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BOC 的本地化字符串。
        /// </summary>
        internal static string BankBOC {
            get {
                return ResourceManager.GetString("BankBOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CCB 的本地化字符串。
        /// </summary>
        internal static string BankCCB {
            get {
                return ResourceManager.GetString("BankCCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CEB 的本地化字符串。
        /// </summary>
        internal static string BankCEB {
            get {
                return ResourceManager.GetString("BankCEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CIB 的本地化字符串。
        /// </summary>
        internal static string BankCIB {
            get {
                return ResourceManager.GetString("BankCIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CMB 的本地化字符串。
        /// </summary>
        internal static string BankCMB {
            get {
                return ResourceManager.GetString("BankCMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CMBC 的本地化字符串。
        /// </summary>
        internal static string BankCMBC {
            get {
                return ResourceManager.GetString("BankCMBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ECITIC 的本地化字符串。
        /// </summary>
        internal static string BankECITIC {
            get {
                return ResourceManager.GetString("BankECITIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GDB 的本地化字符串。
        /// </summary>
        internal static string BankGDB {
            get {
                return ResourceManager.GetString("BankGDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HXB 的本地化字符串。
        /// </summary>
        internal static string BankHXB {
            get {
                return ResourceManager.GetString("BankHXB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ICBC 的本地化字符串。
        /// </summary>
        internal static string BankICBC {
            get {
                return ResourceManager.GetString("BankICBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OtherBank 的本地化字符串。
        /// </summary>
        internal static string BankOtherBank {
            get {
                return ResourceManager.GetString("BankOtherBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PAB 的本地化字符串。
        /// </summary>
        internal static string BankPAB {
            get {
                return ResourceManager.GetString("BankPAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PSBC 的本地化字符串。
        /// </summary>
        internal static string BankPSBC {
            get {
                return ResourceManager.GetString("BankPSBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SPDB 的本地化字符串。
        /// </summary>
        internal static string BankSPDB {
            get {
                return ResourceManager.GetString("BankSPDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can not transfer to your self 的本地化字符串。
        /// </summary>
        internal static string cannotTransferToYourSelf {
            get {
                return ResourceManager.GetString("cannotTransferToYourSelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose dotpay , Choose easy life 的本地化字符串。
        /// </summary>
        internal static string ChooseDotpayChooseEasyLife {
            get {
                return ResourceManager.GetString("ChooseDotpayChooseEasyLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Continue deposit 的本地化字符串。
        /// </summary>
        internal static string continueDeposit {
            get {
                return ResourceManager.GetString("continueDeposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CNY 的本地化字符串。
        /// </summary>
        internal static string CurrencyTypeCny {
            get {
                return ResourceManager.GetString("CurrencyTypeCny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USD 的本地化字符串。
        /// </summary>
        internal static string CurrencyTypeUsd {
            get {
                return ResourceManager.GetString("CurrencyTypeUsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deposit Result 的本地化字符串。
        /// </summary>
        internal static string depositResult {
            get {
                return ResourceManager.GetString("depositResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Complete 的本地化字符串。
        /// </summary>
        internal static string DepositStatusCompleted {
            get {
                return ResourceManager.GetString("DepositStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail 的本地化字符串。
        /// </summary>
        internal static string DepositStatusFail {
            get {
                return ResourceManager.GetString("DepositStatusFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pending 的本地化字符串。
        /// </summary>
        internal static string DepositStatusStarted {
            get {
                return ResourceManager.GetString("DepositStatusStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Congratulations , deposit {0} yuan success. 的本地化字符串。
        /// </summary>
        internal static string depositSuccessNotice {
            get {
                return ResourceManager.GetString("depositSuccessNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deposit 的本地化字符串。
        /// </summary>
        internal static string DepositTransaction {
            get {
                return ResourceManager.GetString("DepositTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Don_t_have_an_account_yet_ {
            get {
                return ResourceManager.GetString("Don\'t have an account yet?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dotpay is xxxx. 的本地化字符串。
        /// </summary>
        internal static string DotpayDescription {
            get {
                return ResourceManager.GetString("DotpayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dotpay 的本地化字符串。
        /// </summary>
        internal static string DotpayLogoTitle {
            get {
                return ResourceManager.GetString("DotpayLogoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid result. 的本地化字符串。
        /// </summary>
        internal static string easypayInvlidResult {
            get {
                return ResourceManager.GetString("easypayInvlidResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Email_already_exists_ {
            get {
                return ResourceManager.GetString("Email already exists.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Enjoy_our_great_service {
            get {
                return ResourceManager.GetString("Enjoy our great service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail Reason : 的本地化字符串。
        /// </summary>
        internal static string FailReason {
            get {
                return ResourceManager.GetString("FailReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Forget_password_ {
            get {
                return ResourceManager.GetString("Forget password?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CertificateOfOfficer 的本地化字符串。
        /// </summary>
        internal static string IdNoTypeCertificateOfOfficer {
            get {
                return ResourceManager.GetString("IdNoTypeCertificateOfOfficer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HKAndMacauResidentsPass 的本地化字符串。
        /// </summary>
        internal static string IdNoTypeHKAndMacauResidentsPass {
            get {
                return ResourceManager.GetString("IdNoTypeHKAndMacauResidentsPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IdentificationCard 的本地化字符串。
        /// </summary>
        internal static string IdNoTypeIdentificationCard {
            get {
                return ResourceManager.GetString("IdNoTypeIdentificationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Passport 的本地化字符串。
        /// </summary>
        internal static string IdNoTypePassport {
            get {
                return ResourceManager.GetString("IdNoTypePassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TaiwanResidentsPass 的本地化字符串。
        /// </summary>
        internal static string IdNoTypeTaiwanResidentsPass {
            get {
                return ResourceManager.GetString("IdNoTypeTaiwanResidentsPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Make pay easy , Make pay cool. 的本地化字符串。
        /// </summary>
        internal static string indexBannerPayeasyPayCool {
            get {
                return ResourceManager.GetString("indexBannerPayeasyPayCool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Invalid_amount {
            get {
                return ResourceManager.GetString("Invalid amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Invalid_receiver_account {
            get {
                return ResourceManager.GetString("Invalid receiver account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid alipay account 的本地化字符串。
        /// </summary>
        internal static string invalidAlipayAccount {
            get {
                return ResourceManager.GetString("invalidAlipayAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid bank account 的本地化字符串。
        /// </summary>
        internal static string invalidBankAccount {
            get {
                return ResourceManager.GetString("invalidBankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Invlid_activation_link_ {
            get {
                return ResourceManager.GetString("Invlid activation link.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Login_fail_too_much_times_You_can_try_again_1_hour_later_ {
            get {
                return ResourceManager.GetString("Login fail too much times.You can try again 1 hour later.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Login_name_already_exists_ {
            get {
                return ResourceManager.GetString("Login name already exists.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Login_name_or_password_error__You_can_try__0__times_ {
            get {
                return ResourceManager.GetString("Login name or password error. You can try {0} times.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string loginBtnText {
            get {
                return ResourceManager.GetString("loginBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string loginFieldPassword {
            get {
                return ResourceManager.GetString("loginFieldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string loginFieldPasswordPlaceholder {
            get {
                return ResourceManager.GetString("loginFieldPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        internal static string loginFieldUserName {
            get {
                return ResourceManager.GetString("loginFieldUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login name or email 的本地化字符串。
        /// </summary>
        internal static string loginFieldUserNamePlaceholder {
            get {
                return ResourceManager.GetString("loginFieldUserNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string order_amount_not_match_ {
            get {
                return ResourceManager.GetString("order amount not match.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PaywayAlipay {
            get {
                return ResourceManager.GetString("PaywayAlipay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PaywayBank {
            get {
                return ResourceManager.GetString("PaywayBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PaywayDotpay {
            get {
                return ResourceManager.GetString("PaywayDotpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PaywayEasyPay {
            get {
                return ResourceManager.GetString("PaywayEasyPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PaywayRipple {
            get {
                return ResourceManager.GetString("PaywayRipple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PaywayTenpay {
            get {
                return ResourceManager.GetString("PaywayTenpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Receiver_Account_ {
            get {
                return ResourceManager.GetString("Receiver Account:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Register_to {
            get {
                return ResourceManager.GetString("Register to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are about 30 seconds away from using Dotpay. Good choice! 的本地化字符串。
        /// </summary>
        internal static string registerDotpayDescription {
            get {
                return ResourceManager.GetString("registerDotpayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Password 的本地化字符串。
        /// </summary>
        internal static string registerFieldConfirmPassword {
            get {
                return ResourceManager.GetString("registerFieldConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm password 的本地化字符串。
        /// </summary>
        internal static string registerFieldConfirmPasswordPlaceholder {
            get {
                return ResourceManager.GetString("registerFieldConfirmPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        internal static string registerFieldEmail {
            get {
                return ResourceManager.GetString("registerFieldEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email Address 的本地化字符串。
        /// </summary>
        internal static string registerFieldEmailPlaceholder {
            get {
                return ResourceManager.GetString("registerFieldEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login Name 的本地化字符串。
        /// </summary>
        internal static string registerFieldLoginName {
            get {
                return ResourceManager.GetString("registerFieldLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loginname 的本地化字符串。
        /// </summary>
        internal static string registerFieldLoginNamePlaceholder {
            get {
                return ResourceManager.GetString("registerFieldLoginNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string registerFieldPassword {
            get {
                return ResourceManager.GetString("registerFieldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string registerFieldPasswordPlaceholder {
            get {
                return ResourceManager.GetString("registerFieldPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return my dotpay 的本地化字符串。
        /// </summary>
        internal static string returnToI {
            get {
                return ResourceManager.GetString("returnToI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Sign_In {
            get {
                return ResourceManager.GetString("Sign In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Sign_in_to {
            get {
                return ResourceManager.GetString("Sign in to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Sign_Up {
            get {
                return ResourceManager.GetString("Sign Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Error 的本地化字符串。
        /// </summary>
        internal static string systemError {
            get {
                return ResourceManager.GetString("systemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry,please try again later 的本地化字符串。
        /// </summary>
        internal static string systemProcessError {
            get {
                return ResourceManager.GetString("systemProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string transfer_money_to_anywhere {
            get {
                return ResourceManager.GetString("transfer money to anywhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account balance not enough 的本地化字符串。
        /// </summary>
        internal static string transferBalanceNotEnough {
            get {
                return ResourceManager.GetString("transferBalanceNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment password error, if fail 3 times, you only can try again 5 hour later 的本地化字符串。
        /// </summary>
        internal static string transferPaymentPasswordError {
            get {
                return ResourceManager.GetString("transferPaymentPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment password max error time,please retry 5 hours later 的本地化字符串。
        /// </summary>
        internal static string transferPaymentPasswordMaxErrorTime {
            get {
                return ResourceManager.GetString("transferPaymentPasswordMaxErrorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please set payment password first 的本地化字符串。
        /// </summary>
        internal static string transferPaymentPasswordNotInit {
            get {
                return ResourceManager.GetString("transferPaymentPasswordNotInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Receiver account has not identity info 的本地化字符串。
        /// </summary>
        internal static string transferReceiverUnauth {
            get {
                return ResourceManager.GetString("transferReceiverUnauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transfer 的本地化字符串。
        /// </summary>
        internal static string TransferTransaction {
            get {
                return ResourceManager.GetString("TransferTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string TransferTransactionStatusCanceled {
            get {
                return ResourceManager.GetString("TransferTransactionStatusCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string TransferTransactionStatusCompleted {
            get {
                return ResourceManager.GetString("TransferTransactionStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail 的本地化字符串。
        /// </summary>
        internal static string TransferTransactionStatusFailed {
            get {
                return ResourceManager.GetString("TransferTransactionStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing 的本地化字符串。
        /// </summary>
        internal static string TransferTransactionStatusLockeByProcessor {
            get {
                return ResourceManager.GetString("TransferTransactionStatusLockeByProcessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing 的本地化字符串。
        /// </summary>
        internal static string TransferTransactionStatusPreparationCompleted {
            get {
                return ResourceManager.GetString("TransferTransactionStatusPreparationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing 的本地化字符串。
        /// </summary>
        internal static string TransferTransactionStatusSubmited {
            get {
                return ResourceManager.GetString("TransferTransactionStatusSubmited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Unkown_Exception_Please_refresh_page_and_retry_ {
            get {
                return ResourceManager.GetString("Unkown Exception,Please refresh page and retry.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please verify your identity first 的本地化字符串。
        /// </summary>
        internal static string verifyIdentityFirst {
            get {
                return ResourceManager.GetString("verifyIdentityFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View deposit records 的本地化字符串。
        /// </summary>
        internal static string viewDepositRecord {
            get {
                return ResourceManager.GetString("viewDepositRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Welcome_to_dotpay {
            get {
                return ResourceManager.GetString("Welcome to dotpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send mail too Frequently,Please resend after 15 minutes. 的本地化字符串。
        /// </summary>
        internal static string You_can_send_active_email_after_15_minutes_ {
            get {
                return ResourceManager.GetString("You can send active email after 15 minutes.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your quick pay experts 的本地化字符串。
        /// </summary>
        internal static string YourQuickPayExperts {
            get {
                return ResourceManager.GetString("YourQuickPayExperts", resourceCulture);
            }
        }
    }
}
