//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace Dotpay.Actor.Service.Interfaces
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using System.Reflection;
    using Orleans.Serialization;
    using Dotpay.Actor.Service.Interfaces;
    using Dotpay.Common;
    using Orleans;
    using Orleans.Runtime;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class RippleQuoteServiceFactory
    {
        

                        public static Dotpay.Actor.Service.Interfaces.IRippleQuoteService GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Dotpay.Actor.Service.Interfaces.IRippleQuoteService), 2133055338, primaryKey));
                        }

                        public static Dotpay.Actor.Service.Interfaces.IRippleQuoteService GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Dotpay.Actor.Service.Interfaces.IRippleQuoteService), 2133055338, primaryKey, grainClassNamePrefix));
                        }

            public static Dotpay.Actor.Service.Interfaces.IRippleQuoteService Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return RippleQuoteServiceReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Dotpay.Actor.Service.Interfaces.Dotpay.Actor.Service.Interfaces.IRippleQuoteServi" +
            "ce")]
        internal class RippleQuoteServiceReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Dotpay.Actor.Service.Interfaces.IRippleQuoteService
        {
            

            public static Dotpay.Actor.Service.Interfaces.IRippleQuoteService Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Dotpay.Actor.Service.Interfaces.IRippleQuoteService) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Dotpay.Actor.Service.Interfaces.IRippleQuoteService), (global::Orleans.Runtime.GrainReference gr) => { return new RippleQuoteServiceReference(gr);}, grainRef, 2133055338);
            }
            
            protected internal RippleQuoteServiceReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal RippleQuoteServiceReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 2133055338;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Dotpay.Actor.Service.Interfaces.Dotpay.Actor.Service.Interfaces.IRippleQuoteServi" +
                        "ce";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                RippleQuoteServiceReference input = ((RippleQuoteServiceReference)(original));
                return ((RippleQuoteServiceReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                RippleQuoteServiceReference input = ((RippleQuoteServiceReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return RippleQuoteServiceReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return ((interfaceId == this.InterfaceId) 
                            || (interfaceId == 1928988877));
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return RippleQuoteServiceMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task<Dotpay.Actor.Service.Interfaces.QuoteResult> Dotpay.Actor.Service.Interfaces.IRippleQuoteService.Quote(Dotpay.Actor.Interfaces.TransferTargetInfo @transferTargetInfo, decimal @amount, string @memo)
            {

                return base.InvokeMethodAsync<Dotpay.Actor.Service.Interfaces.QuoteResult>(-1483681480, new object[] {@transferTargetInfo, @amount, @memo} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Dotpay.Actor.Service.Interfaces.Dotpay.Actor.Service.Interfaces.IRippleQuoteServi" +
        "ce", 2133055338)]
    internal class RippleQuoteServiceMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 2133055338;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 2133055338:  // IRippleQuoteService
                        switch (methodId)
                        {
                            case -1483681480: 
                                return ((IRippleQuoteService)grain).Quote((Dotpay.Actor.Interfaces.TransferTargetInfo)arguments[0], (Decimal)arguments[1], (String)arguments[2]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }case 1928988877:  // IGrainWithIntegerKey
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 2133055338:  // IRippleQuoteService
                    switch (methodId)
                    {
                        case -1483681480:
                            return "Quote";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }
                case 1928988877:  // IGrainWithIntegerKey
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Dotpay_Actor_Service_Interfaces_QuoteResultSerialization
    {
        
        static Dotpay_Actor_Service_Interfaces_QuoteResultSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Dotpay.Actor.Service.Interfaces.QuoteResult input = ((Dotpay.Actor.Service.Interfaces.QuoteResult)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.ErrorCode, stream, typeof(Dotpay.Common.ErrorCode));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Quote, stream, typeof(Dotpay.Actor.Service.Interfaces.Quote));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Dotpay.Actor.Service.Interfaces.QuoteResult result = ((Dotpay.Actor.Service.Interfaces.QuoteResult)(System.Runtime.Serialization.FormatterServices.GetUninitializedObject(typeof(Dotpay.Actor.Service.Interfaces.QuoteResult))));
            result.ErrorCode = ((Dotpay.Common.ErrorCode)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Dotpay.Common.ErrorCode), stream)));
            result.Quote = ((Dotpay.Actor.Service.Interfaces.Quote)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Dotpay.Actor.Service.Interfaces.Quote), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Dotpay.Actor.Service.Interfaces.QuoteResult), DeepCopier, Serializer, Deserializer);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Dotpay_Actor_Service_Interfaces_QuoteSerialization
    {
        
        static Dotpay_Actor_Service_Interfaces_QuoteSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Dotpay.Actor.Service.Interfaces.Quote input = ((Dotpay.Actor.Service.Interfaces.Quote)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.DestinationTag, stream, typeof(int));
            Orleans.Serialization.SerializationManager.SerializeInner(input.InvoiceId, stream, typeof(string));
            Orleans.Serialization.SerializationManager.SerializeInner(input.SendAmount, stream, typeof(decimal));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Dotpay.Actor.Service.Interfaces.Quote result = ((Dotpay.Actor.Service.Interfaces.Quote)(System.Runtime.Serialization.FormatterServices.GetUninitializedObject(typeof(Dotpay.Actor.Service.Interfaces.Quote))));
            result.DestinationTag = ((int)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(int), stream)));
            result.InvoiceId = ((string)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(string), stream)));
            result.SendAmount = ((decimal)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(decimal), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Dotpay.Actor.Service.Interfaces.Quote), DeepCopier, Serializer, Deserializer);
        }
    }
}
namespace Dotpay.Actor.Interfaces
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using System.Reflection;
    using Orleans.Serialization;
    using Dotpay.Actor.Interfaces;
    using Dotpay.Common.Enum;
    using Orleans;
    using Orleans.Runtime;
    using Dotpay.Common;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class SystemSettingFactory
    {
        

                        public static Dotpay.Actor.Interfaces.ISystemSetting GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Dotpay.Actor.Interfaces.ISystemSetting), 468577895, primaryKey));
                        }

                        public static Dotpay.Actor.Interfaces.ISystemSetting GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Dotpay.Actor.Interfaces.ISystemSetting), 468577895, primaryKey, grainClassNamePrefix));
                        }

            public static Dotpay.Actor.Interfaces.ISystemSetting Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return SystemSettingReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Dotpay.Actor.Interfaces.Dotpay.Actor.Interfaces.ISystemSetting")]
        internal class SystemSettingReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Dotpay.Actor.Interfaces.ISystemSetting
        {
            

            public static Dotpay.Actor.Interfaces.ISystemSetting Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Dotpay.Actor.Interfaces.ISystemSetting) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Dotpay.Actor.Interfaces.ISystemSetting), (global::Orleans.Runtime.GrainReference gr) => { return new SystemSettingReference(gr);}, grainRef, 468577895);
            }
            
            protected internal SystemSettingReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal SystemSettingReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 468577895;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Dotpay.Actor.Interfaces.Dotpay.Actor.Interfaces.ISystemSetting";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                SystemSettingReference input = ((SystemSettingReference)(original));
                return ((SystemSettingReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                SystemSettingReference input = ((SystemSettingReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return SystemSettingReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return ((interfaceId == this.InterfaceId) 
                            || (interfaceId == 1928988877));
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return SystemSettingMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task<Dotpay.Actor.Interfaces.RippleToFinancialInstitutionSetting> Dotpay.Actor.Interfaces.ISystemSetting.GetRippleToFinancialInstitutionSetting()
            {

                return base.InvokeMethodAsync<Dotpay.Actor.Interfaces.RippleToFinancialInstitutionSetting>(1231346134, new object[] {} );
            }
            
            System.Threading.Tasks.Task Dotpay.Actor.Interfaces.ISystemSetting.UpdateRippleToFinancialInstitutionSetting(Dotpay.Actor.Interfaces.RippleToFinancialInstitutionSetting @setting, System.Guid @updateBy)
            {

                return base.InvokeMethodAsync<object>(-8345625, new object[] {@setting, @updateBy} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Dotpay.Actor.Interfaces.Dotpay.Actor.Interfaces.ISystemSetting", 468577895)]
    internal class SystemSettingMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 468577895;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 468577895:  // ISystemSetting
                        switch (methodId)
                        {
                            case 1231346134: 
                                return ((ISystemSetting)grain).GetRippleToFinancialInstitutionSetting().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -8345625: 
                                return ((ISystemSetting)grain).UpdateRippleToFinancialInstitutionSetting((RippleToFinancialInstitutionSetting)arguments[0], (Guid)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }case 1928988877:  // IGrainWithIntegerKey
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 468577895:  // ISystemSetting
                    switch (methodId)
                    {
                        case 1231346134:
                            return "GetRippleToFinancialInstitutionSetting";
                    case -8345625:
                            return "UpdateRippleToFinancialInstitutionSetting";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }
                case 1928988877:  // IGrainWithIntegerKey
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class AtomicIncrementFactory
    {
        

                        public static Dotpay.Actor.Interfaces.IAtomicIncrement GetGrain(System.String primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Dotpay.Actor.Interfaces.IAtomicIncrement), -130975188, primaryKey));
                        }

                        public static Dotpay.Actor.Interfaces.IAtomicIncrement GetGrain(System.String primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Dotpay.Actor.Interfaces.IAtomicIncrement), -130975188, primaryKey, grainClassNamePrefix));
                        }

            public static Dotpay.Actor.Interfaces.IAtomicIncrement Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return AtomicIncrementReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Dotpay.Actor.Interfaces.Dotpay.Actor.Interfaces.IAtomicIncrement")]
        internal class AtomicIncrementReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Dotpay.Actor.Interfaces.IAtomicIncrement
        {
            

            public static Dotpay.Actor.Interfaces.IAtomicIncrement Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Dotpay.Actor.Interfaces.IAtomicIncrement) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Dotpay.Actor.Interfaces.IAtomicIncrement), (global::Orleans.Runtime.GrainReference gr) => { return new AtomicIncrementReference(gr);}, grainRef, -130975188);
            }
            
            protected internal AtomicIncrementReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal AtomicIncrementReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return -130975188;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Dotpay.Actor.Interfaces.Dotpay.Actor.Interfaces.IAtomicIncrement";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                AtomicIncrementReference input = ((AtomicIncrementReference)(original));
                return ((AtomicIncrementReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                AtomicIncrementReference input = ((AtomicIncrementReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return AtomicIncrementReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return ((interfaceId == this.InterfaceId) 
                            || (interfaceId == -1277021679));
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return AtomicIncrementMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task<int> Dotpay.Actor.Interfaces.IAtomicIncrement.GetNext()
            {

                return base.InvokeMethodAsync<System.Int32>(-629872769, new object[] {} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Dotpay.Actor.Interfaces.Dotpay.Actor.Interfaces.IAtomicIncrement", -130975188)]
    internal class AtomicIncrementMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return -130975188;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -130975188:  // IAtomicIncrement
                        switch (methodId)
                        {
                            case -629872769: 
                                return ((IAtomicIncrement)grain).GetNext().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }case -1277021679:  // IGrainWithStringKey
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -130975188:  // IAtomicIncrement
                    switch (methodId)
                    {
                        case -629872769:
                            return "GetNext";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }
                case -1277021679:  // IGrainWithStringKey
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class TransferTransactionToFinancialInstitutionFactory
    {
        

                        public static Dotpay.Actor.Interfaces.ITransferTransactionToFinancialInstitution GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Dotpay.Actor.Interfaces.ITransferTransactionToFinancialInstitution), -1707200787, primaryKey));
                        }

                        public static Dotpay.Actor.Interfaces.ITransferTransactionToFinancialInstitution GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Dotpay.Actor.Interfaces.ITransferTransactionToFinancialInstitution), -1707200787, primaryKey, grainClassNamePrefix));
                        }

            public static Dotpay.Actor.Interfaces.ITransferTransactionToFinancialInstitution Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return TransferTransactionToFinancialInstitutionReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Dotpay.Actor.Interfaces.Dotpay.Actor.Interfaces.ITransferTransactionToFinancialIn" +
            "stitution")]
        internal class TransferTransactionToFinancialInstitutionReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Dotpay.Actor.Interfaces.ITransferTransactionToFinancialInstitution
        {
            

            public static Dotpay.Actor.Interfaces.ITransferTransactionToFinancialInstitution Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Dotpay.Actor.Interfaces.ITransferTransactionToFinancialInstitution) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Dotpay.Actor.Interfaces.ITransferTransactionToFinancialInstitution), (global::Orleans.Runtime.GrainReference gr) => { return new TransferTransactionToFinancialInstitutionReference(gr);}, grainRef, -1707200787);
            }
            
            protected internal TransferTransactionToFinancialInstitutionReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal TransferTransactionToFinancialInstitutionReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return -1707200787;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Dotpay.Actor.Interfaces.Dotpay.Actor.Interfaces.ITransferTransactionToFinancialIn" +
                        "stitution";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                TransferTransactionToFinancialInstitutionReference input = ((TransferTransactionToFinancialInstitutionReference)(original));
                return ((TransferTransactionToFinancialInstitutionReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                TransferTransactionToFinancialInstitutionReference input = ((TransferTransactionToFinancialInstitutionReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return TransferTransactionToFinancialInstitutionReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return ((interfaceId == this.InterfaceId) 
                            || (interfaceId == -1097320095));
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return TransferTransactionToFinancialInstitutionMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task Dotpay.Actor.Interfaces.ITransferTransactionToFinancialInstitution.Initialize(Dotpay.Actor.Interfaces.TransferSourceInfo @transferSourceInfo, Dotpay.Actor.Interfaces.TransferTargetInfo @transferTargetInfo, decimal @amount, string @memo)
            {

                return base.InvokeMethodAsync<object>(1956659292, new object[] {@transferSourceInfo, @transferTargetInfo, @amount, @memo} );
            }
            
            System.Threading.Tasks.Task<Dotpay.Common.ErrorCode> Dotpay.Actor.Interfaces.ITransferTransactionToFinancialInstitution.MarkAsProcessing(System.Guid @processorUserId)
            {

                return base.InvokeMethodAsync<Dotpay.Common.ErrorCode>(-622970921, new object[] {@processorUserId} );
            }
            
            System.Threading.Tasks.Task<Dotpay.Common.ErrorCode> Dotpay.Actor.Interfaces.ITransferTransactionToFinancialInstitution.MarkAsCompleted(System.Guid @processorUserId)
            {

                return base.InvokeMethodAsync<Dotpay.Common.ErrorCode>(1022064884, new object[] {@processorUserId} );
            }
            
            System.Threading.Tasks.Task<Dotpay.Common.ErrorCode> Dotpay.Actor.Interfaces.ITransferTransactionToFinancialInstitution.MarkAsFailed(string @reason, System.Guid @processorUserId)
            {

                return base.InvokeMethodAsync<Dotpay.Common.ErrorCode>(-942011897, new object[] {@reason, @processorUserId} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Dotpay.Actor.Interfaces.Dotpay.Actor.Interfaces.ITransferTransactionToFinancialIn" +
        "stitution", -1707200787)]
    internal class TransferTransactionToFinancialInstitutionMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return -1707200787;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case -1707200787:  // ITransferTransactionToFinancialInstitution
                        switch (methodId)
                        {
                            case 1956659292: 
                                return ((ITransferTransactionToFinancialInstitution)grain).Initialize((TransferSourceInfo)arguments[0], (TransferTargetInfo)arguments[1], (Decimal)arguments[2], (String)arguments[3]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -622970921: 
                                return ((ITransferTransactionToFinancialInstitution)grain).MarkAsProcessing((Guid)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 1022064884: 
                                return ((ITransferTransactionToFinancialInstitution)grain).MarkAsCompleted((Guid)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -942011897: 
                                return ((ITransferTransactionToFinancialInstitution)grain).MarkAsFailed((String)arguments[0], (Guid)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }case -1097320095:  // IGrainWithGuidKey
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case -1707200787:  // ITransferTransactionToFinancialInstitution
                    switch (methodId)
                    {
                        case 1956659292:
                            return "Initialize";
                    case -622970921:
                            return "MarkAsProcessing";
                    case 1022064884:
                            return "MarkAsCompleted";
                    case -942011897:
                            return "MarkAsFailed";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }
                case -1097320095:  // IGrainWithGuidKey
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class UserFactory
    {
        

                        public static Dotpay.Actor.Interfaces.IUser GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Dotpay.Actor.Interfaces.IUser), 1071184334, primaryKey));
                        }

                        public static Dotpay.Actor.Interfaces.IUser GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Dotpay.Actor.Interfaces.IUser), 1071184334, primaryKey, grainClassNamePrefix));
                        }

            public static Dotpay.Actor.Interfaces.IUser Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return UserReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Dotpay.Actor.Interfaces.Dotpay.Actor.Interfaces.IUser")]
        internal class UserReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Dotpay.Actor.Interfaces.IUser
        {
            

            public static Dotpay.Actor.Interfaces.IUser Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Dotpay.Actor.Interfaces.IUser) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Dotpay.Actor.Interfaces.IUser), (global::Orleans.Runtime.GrainReference gr) => { return new UserReference(gr);}, grainRef, 1071184334);
            }
            
            protected internal UserReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal UserReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 1071184334;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Dotpay.Actor.Interfaces.Dotpay.Actor.Interfaces.IUser";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                UserReference input = ((UserReference)(original));
                return ((UserReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                UserReference input = ((UserReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return UserReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return ((interfaceId == this.InterfaceId) 
                            || (interfaceId == -1097320095));
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return UserMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task<Dotpay.Common.ErrorCode> Dotpay.Actor.Interfaces.IUser.PreRegister(string @email)
            {

                return base.InvokeMethodAsync<Dotpay.Common.ErrorCode>(1528301820, new object[] {@email} );
            }
            
            System.Threading.Tasks.Task Dotpay.Actor.Interfaces.IUser.Initialize(string @userAccount, string @loginPassword, string @tradePassword)
            {

                return base.InvokeMethodAsync<object>(-1600852723, new object[] {@userAccount, @loginPassword, @tradePassword} );
            }
            
            System.Threading.Tasks.Task<Dotpay.Common.ErrorCode> Dotpay.Actor.Interfaces.IUser.Login(string @loginPassword, string @ip)
            {

                return base.InvokeMethodAsync<Dotpay.Common.ErrorCode>(1415878300, new object[] {@loginPassword, @ip} );
            }
            
            System.Threading.Tasks.Task Dotpay.Actor.Interfaces.IUser.Lock(System.Guid @operatorId, string @reason)
            {

                return base.InvokeMethodAsync<object>(1046983731, new object[] {@operatorId, @reason} );
            }
            
            System.Threading.Tasks.Task Dotpay.Actor.Interfaces.IUser.Unlock(System.Guid @operatorId, string @reason)
            {

                return base.InvokeMethodAsync<object>(-962125716, new object[] {@operatorId, @reason} );
            }
            
            System.Threading.Tasks.Task Dotpay.Actor.Interfaces.IUser.SetMobile(string @mobile, string @otpKey, string @otp)
            {

                return base.InvokeMethodAsync<object>(1865607900, new object[] {@mobile, @otpKey, @otp} );
            }
            
            System.Threading.Tasks.Task Dotpay.Actor.Interfaces.IUser.VeirfyIdentity(string @fullName, Dotpay.Common.IdNoType @idNoType, string @idNo)
            {

                return base.InvokeMethodAsync<object>(193253814, new object[] {@fullName, @idNoType, @idNo} );
            }
            
            System.Threading.Tasks.Task<bool> Dotpay.Actor.Interfaces.IUser.CheckLoginPassword(string @loginPassword)
            {

                return base.InvokeMethodAsync<System.Boolean>(-1388525298, new object[] {@loginPassword} );
            }
            
            System.Threading.Tasks.Task<bool> Dotpay.Actor.Interfaces.IUser.CheckPaymentPassword(string @tradePassword)
            {

                return base.InvokeMethodAsync<System.Boolean>(-1286558509, new object[] {@tradePassword} );
            }
            
            System.Threading.Tasks.Task<Dotpay.Common.ErrorCode> Dotpay.Actor.Interfaces.IUser.ChangeLoginPassword(string @oldLoginPassword, string @newLoginPassword)
            {

                return base.InvokeMethodAsync<Dotpay.Common.ErrorCode>(-1632402458, new object[] {@oldLoginPassword, @newLoginPassword} );
            }
            
            System.Threading.Tasks.Task<Dotpay.Common.ErrorCode> Dotpay.Actor.Interfaces.IUser.ChangePaymentPassword(string @oldPaymentPassword, string @newPaymentPassword, string @smsVerifyCode)
            {

                return base.InvokeMethodAsync<Dotpay.Common.ErrorCode>(385697540, new object[] {@oldPaymentPassword, @newPaymentPassword, @smsVerifyCode} );
            }
            
            System.Threading.Tasks.Task Dotpay.Actor.Interfaces.IUser.AssignRoles(System.Guid @operatorId, System.Collections.Generic.IEnumerable<ManagerType> @roles)
            {

                return base.InvokeMethodAsync<object>(953637368, new object[] {@operatorId, @roles} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Dotpay.Actor.Interfaces.Dotpay.Actor.Interfaces.IUser", 1071184334)]
    internal class UserMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 1071184334;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 1071184334:  // IUser
                        switch (methodId)
                        {
                            case 1528301820: 
                                return ((IUser)grain).PreRegister((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -1600852723: 
                                return ((IUser)grain).Initialize((String)arguments[0], (String)arguments[1], (String)arguments[2]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 1415878300: 
                                return ((IUser)grain).Login((String)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 1046983731: 
                                return ((IUser)grain).Lock((Guid)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -962125716: 
                                return ((IUser)grain).Unlock((Guid)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 1865607900: 
                                return ((IUser)grain).SetMobile((String)arguments[0], (String)arguments[1], (String)arguments[2]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 193253814: 
                                return ((IUser)grain).VeirfyIdentity((String)arguments[0], (IdNoType)arguments[1], (String)arguments[2]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1388525298: 
                                return ((IUser)grain).CheckLoginPassword((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -1286558509: 
                                return ((IUser)grain).CheckPaymentPassword((String)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -1632402458: 
                                return ((IUser)grain).ChangeLoginPassword((String)arguments[0], (String)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 385697540: 
                                return ((IUser)grain).ChangePaymentPassword((String)arguments[0], (String)arguments[1], (String)arguments[2]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 953637368: 
                                return ((IUser)grain).AssignRoles((Guid)arguments[0], (System.Collections.Generic.IEnumerable<ManagerType>)arguments[1]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }case -1097320095:  // IGrainWithGuidKey
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 1071184334:  // IUser
                    switch (methodId)
                    {
                        case 1528301820:
                            return "PreRegister";
                    case -1600852723:
                            return "Initialize";
                    case 1415878300:
                            return "Login";
                    case 1046983731:
                            return "Lock";
                    case -962125716:
                            return "Unlock";
                    case 1865607900:
                            return "SetMobile";
                    case 193253814:
                            return "VeirfyIdentity";
                    case -1388525298:
                            return "CheckLoginPassword";
                    case -1286558509:
                            return "CheckPaymentPassword";
                    case -1632402458:
                            return "ChangeLoginPassword";
                    case 385697540:
                            return "ChangePaymentPassword";
                    case 953637368:
                            return "AssignRoles";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }
                case -1097320095:  // IGrainWithGuidKey
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Dotpay_Actor_Interfaces_TransferTargetInfoSerialization
    {
        
        static Dotpay_Actor_Interfaces_TransferTargetInfoSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Dotpay.Actor.Interfaces.TransferTargetInfo input = ((Dotpay.Actor.Interfaces.TransferTargetInfo)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.DestinationAccount, stream, typeof(string));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Payway, stream, typeof(Dotpay.Common.Enum.Payway));
            Orleans.Serialization.SerializationManager.SerializeInner(input.RealName, stream, typeof(string));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Dotpay.Actor.Interfaces.TransferTargetInfo result = new Dotpay.Actor.Interfaces.TransferTargetInfo();
            result.DestinationAccount = ((string)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(string), stream)));
            result.Payway = ((Dotpay.Common.Enum.Payway)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Dotpay.Common.Enum.Payway), stream)));
            result.RealName = ((string)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(string), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Dotpay.Actor.Interfaces.TransferTargetInfo), DeepCopier, Serializer, Deserializer);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Dotpay_Actor_Interfaces_RippleToFinancialInstitutionSettingSerialization
    {
        
        static Dotpay_Actor_Interfaces_RippleToFinancialInstitutionSettingSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Dotpay.Actor.Interfaces.RippleToFinancialInstitutionSetting input = ((Dotpay.Actor.Interfaces.RippleToFinancialInstitutionSetting)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.FeeRate, stream, typeof(decimal));
            Orleans.Serialization.SerializationManager.SerializeInner(input.FixedFee, stream, typeof(decimal));
            Orleans.Serialization.SerializationManager.SerializeInner(input.MaxAmount, stream, typeof(decimal));
            Orleans.Serialization.SerializationManager.SerializeInner(input.MaxFee, stream, typeof(System.Nullable<System.Decimal>));
            Orleans.Serialization.SerializationManager.SerializeInner(input.MinAmount, stream, typeof(decimal));
            Orleans.Serialization.SerializationManager.SerializeInner(input.MinFee, stream, typeof(System.Nullable<System.Decimal>));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Dotpay.Actor.Interfaces.RippleToFinancialInstitutionSetting result = new Dotpay.Actor.Interfaces.RippleToFinancialInstitutionSetting();
            result.FeeRate = ((decimal)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(decimal), stream)));
            result.FixedFee = ((decimal)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(decimal), stream)));
            result.MaxAmount = ((decimal)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(decimal), stream)));
            result.MaxFee = ((System.Nullable<System.Decimal>)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(System.Nullable<System.Decimal>), stream)));
            result.MinAmount = ((decimal)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(decimal), stream)));
            result.MinFee = ((System.Nullable<System.Decimal>)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(System.Nullable<System.Decimal>), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Dotpay.Actor.Interfaces.RippleToFinancialInstitutionSetting), DeepCopier, Serializer, Deserializer);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Dotpay_Actor_Interfaces_TransferSourceInfoSerialization
    {
        
        static Dotpay_Actor_Interfaces_TransferSourceInfoSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Dotpay.Actor.Interfaces.TransferSourceInfo input = ((Dotpay.Actor.Interfaces.TransferSourceInfo)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Payway, stream, typeof(Dotpay.Common.Enum.Payway));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Dotpay.Actor.Interfaces.TransferSourceInfo result = new Dotpay.Actor.Interfaces.TransferSourceInfo();
            result.Payway = ((Dotpay.Common.Enum.Payway)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Dotpay.Common.Enum.Payway), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Dotpay.Actor.Interfaces.TransferSourceInfo), DeepCopier, Serializer, Deserializer);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Dotpay_Actor_Interfaces_TransferFromRippleInfoSerialization
    {
        
        static Dotpay_Actor_Interfaces_TransferFromRippleInfoSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Dotpay.Actor.Interfaces.TransferFromRippleInfo input = ((Dotpay.Actor.Interfaces.TransferFromRippleInfo)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Payway, stream, typeof(Dotpay.Common.Enum.Payway));
            Orleans.Serialization.SerializationManager.SerializeInner(input.TxId, stream, typeof(string));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Dotpay.Actor.Interfaces.TransferFromRippleInfo result = new Dotpay.Actor.Interfaces.TransferFromRippleInfo();
            result.Payway = ((Dotpay.Common.Enum.Payway)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Dotpay.Common.Enum.Payway), stream)));
            result.TxId = ((string)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(string), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Dotpay.Actor.Interfaces.TransferFromRippleInfo), DeepCopier, Serializer, Deserializer);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Dotpay_Actor_Interfaces_TransferFromDotpayInfoSerialization
    {
        
        static Dotpay_Actor_Interfaces_TransferFromDotpayInfoSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Dotpay.Actor.Interfaces.TransferFromDotpayInfo input = ((Dotpay.Actor.Interfaces.TransferFromDotpayInfo)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.AccountId, stream, typeof(System.Guid));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Payway, stream, typeof(Dotpay.Common.Enum.Payway));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Dotpay.Actor.Interfaces.TransferFromDotpayInfo result = new Dotpay.Actor.Interfaces.TransferFromDotpayInfo();
            result.AccountId = ((System.Guid)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(System.Guid), stream)));
            result.Payway = ((Dotpay.Common.Enum.Payway)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Dotpay.Common.Enum.Payway), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Dotpay.Actor.Interfaces.TransferFromDotpayInfo), DeepCopier, Serializer, Deserializer);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Dotpay_Actor_Interfaces_TransferToTppInfoSerialization
    {
        
        static Dotpay_Actor_Interfaces_TransferToTppInfoSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Dotpay.Actor.Interfaces.TransferToTppInfo input = ((Dotpay.Actor.Interfaces.TransferToTppInfo)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.DestinationAccount, stream, typeof(string));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Payway, stream, typeof(Dotpay.Common.Enum.Payway));
            Orleans.Serialization.SerializationManager.SerializeInner(input.RealName, stream, typeof(string));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Dotpay.Actor.Interfaces.TransferToTppInfo result = new Dotpay.Actor.Interfaces.TransferToTppInfo();
            result.DestinationAccount = ((string)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(string), stream)));
            result.Payway = ((Dotpay.Common.Enum.Payway)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Dotpay.Common.Enum.Payway), stream)));
            result.RealName = ((string)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(string), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Dotpay.Actor.Interfaces.TransferToTppInfo), DeepCopier, Serializer, Deserializer);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Dotpay_Actor_Interfaces_TransferToBankInfoSerialization
    {
        
        static Dotpay_Actor_Interfaces_TransferToBankInfoSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            return original;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Dotpay.Actor.Interfaces.TransferToBankInfo input = ((Dotpay.Actor.Interfaces.TransferToBankInfo)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Bank, stream, typeof(Dotpay.Common.Enum.Bank));
            Orleans.Serialization.SerializationManager.SerializeInner(input.DestinationAccount, stream, typeof(string));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Payway, stream, typeof(Dotpay.Common.Enum.Payway));
            Orleans.Serialization.SerializationManager.SerializeInner(input.RealName, stream, typeof(string));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Dotpay.Actor.Interfaces.TransferToBankInfo result = new Dotpay.Actor.Interfaces.TransferToBankInfo();
            result.Bank = ((Dotpay.Common.Enum.Bank)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Dotpay.Common.Enum.Bank), stream)));
            result.DestinationAccount = ((string)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(string), stream)));
            result.Payway = ((Dotpay.Common.Enum.Payway)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Dotpay.Common.Enum.Payway), stream)));
            result.RealName = ((string)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(string), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Dotpay.Actor.Interfaces.TransferToBankInfo), DeepCopier, Serializer, Deserializer);
        }
    }
}
namespace Dotpay.Actor.Interfaces.Ripple
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using Orleans;
    using Orleans.Runtime;
    using Dotpay.Common;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class RippleToFinancialInstitutionListenerFactory
    {
        

                        public static Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitutionListener GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitutionListener), 661328755, primaryKey));
                        }

                        public static Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitutionListener GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitutionListener), 661328755, primaryKey, grainClassNamePrefix));
                        }

            public static Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitutionListener Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return RippleToFinancialInstitutionListenerReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Dotpay.Actor.Interfaces.Ripple.Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialI" +
            "nstitutionListener")]
        internal class RippleToFinancialInstitutionListenerReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitutionListener
        {
            

            public static Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitutionListener Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitutionListener) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitutionListener), (global::Orleans.Runtime.GrainReference gr) => { return new RippleToFinancialInstitutionListenerReference(gr);}, grainRef, 661328755);
            }
            
            protected internal RippleToFinancialInstitutionListenerReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal RippleToFinancialInstitutionListenerReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 661328755;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Dotpay.Actor.Interfaces.Ripple.Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialI" +
                        "nstitutionListener";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                RippleToFinancialInstitutionListenerReference input = ((RippleToFinancialInstitutionListenerReference)(original));
                return ((RippleToFinancialInstitutionListenerReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                RippleToFinancialInstitutionListenerReference input = ((RippleToFinancialInstitutionListenerReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return RippleToFinancialInstitutionListenerReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return ((interfaceId == this.InterfaceId) 
                            || (interfaceId == 1928988877));
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return RippleToFinancialInstitutionListenerMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitutionListener.Start()
            {

                return base.InvokeMethodAsync<object>(1420312199, new object[] {} );
            }
            
            System.Threading.Tasks.Task Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitutionListener.CompleteRippleToFinancialInstitution(string @invoiceId, int @destinaionTag, string @txId, decimal @amount)
            {

                return base.InvokeMethodAsync<object>(-1041588555, new object[] {@invoiceId, @destinaionTag, @txId, @amount} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Dotpay.Actor.Interfaces.Ripple.Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialI" +
        "nstitutionListener", 661328755)]
    internal class RippleToFinancialInstitutionListenerMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 661328755;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 661328755:  // IRippleToFinancialInstitutionListener
                        switch (methodId)
                        {
                            case 1420312199: 
                                return ((IRippleToFinancialInstitutionListener)grain).Start().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1041588555: 
                                return ((IRippleToFinancialInstitutionListener)grain).CompleteRippleToFinancialInstitution((String)arguments[0], (Int32)arguments[1], (String)arguments[2], (Decimal)arguments[3]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }case 1928988877:  // IGrainWithIntegerKey
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 661328755:  // IRippleToFinancialInstitutionListener
                    switch (methodId)
                    {
                        case 1420312199:
                            return "Start";
                    case -1041588555:
                            return "CompleteRippleToFinancialInstitution";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }
                case 1928988877:  // IGrainWithIntegerKey
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class RippleToFinancialInstitutionFactory
    {
        

                        public static Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitution GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitution), 1793292731, primaryKey));
                        }

                        public static Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitution GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitution), 1793292731, primaryKey, grainClassNamePrefix));
                        }

            public static Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitution Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return RippleToFinancialInstitutionReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Dotpay.Actor.Interfaces.Ripple.Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialI" +
            "nstitution")]
        internal class RippleToFinancialInstitutionReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitution
        {
            

            public static Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitution Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitution) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitution), (global::Orleans.Runtime.GrainReference gr) => { return new RippleToFinancialInstitutionReference(gr);}, grainRef, 1793292731);
            }
            
            protected internal RippleToFinancialInstitutionReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal RippleToFinancialInstitutionReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 1793292731;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Dotpay.Actor.Interfaces.Ripple.Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialI" +
                        "nstitution";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                RippleToFinancialInstitutionReference input = ((RippleToFinancialInstitutionReference)(original));
                return ((RippleToFinancialInstitutionReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                RippleToFinancialInstitutionReference input = ((RippleToFinancialInstitutionReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return RippleToFinancialInstitutionReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return ((interfaceId == this.InterfaceId) 
                            || (interfaceId == 1928988877));
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return RippleToFinancialInstitutionMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitution.Initialize(string @invoiceId, Dotpay.Actor.Interfaces.TransferTargetInfo @transferTargetInfo, decimal @amount, decimal @sendAmount, string @memo)
            {

                return base.InvokeMethodAsync<object>(1788818524, new object[] {@invoiceId, @transferTargetInfo, @amount, @sendAmount, @memo} );
            }
            
            System.Threading.Tasks.Task<Dotpay.Common.ErrorCode> Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialInstitution.Complete(string @invoiceId, string @txId, decimal @sendAmount)
            {

                return base.InvokeMethodAsync<Dotpay.Common.ErrorCode>(-1382115995, new object[] {@invoiceId, @txId, @sendAmount} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.0.0")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Dotpay.Actor.Interfaces.Ripple.Dotpay.Actor.Interfaces.Ripple.IRippleToFinancialI" +
        "nstitution", 1793292731)]
    internal class RippleToFinancialInstitutionMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 1793292731;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 1793292731:  // IRippleToFinancialInstitution
                        switch (methodId)
                        {
                            case 1788818524: 
                                return ((IRippleToFinancialInstitution)grain).Initialize((String)arguments[0], (Dotpay.Actor.Interfaces.TransferTargetInfo)arguments[1], (Decimal)arguments[2], (Decimal)arguments[3], (String)arguments[4]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1382115995: 
                                return ((IRippleToFinancialInstitution)grain).Complete((String)arguments[0], (String)arguments[1], (Decimal)arguments[2]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }case 1928988877:  // IGrainWithIntegerKey
                        switch (methodId)
                        {
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }
            catch(Exception ex)
            {
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 1793292731:  // IRippleToFinancialInstitution
                    switch (methodId)
                    {
                        case 1788818524:
                            return "Initialize";
                    case -1382115995:
                            return "Complete";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }
                case 1928988877:  // IGrainWithIntegerKey
                    switch (methodId)
                    {
                        
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
